version: '3'

tasks:
  setup:
    desc: "Set up the ledger environment with Docker Compose"
    cmds:
      - docker-compose up -d
    silent: false

  run-test:
    desc: "Run the stress test script iteratively using Node.js"
    deps:
      - setup
    cmds:
      - npm run build
      - |
        for i in $(seq 1 100); do
          echo "Iteration $i"
          task formance:reset        
          node ./dist/index.js $i
        done
    silent: true

  clean:
    desc: "Clean up the Docker environment"
    cmds:
      - docker-compose down
    silent: false

  stress-test:
    desc: "Full process: Clean up, set up, run stress test, and clean up again"
    cmds:
      - task clean
      - task setup
      - task run-test
      - task clean


  formance:reset:
    internal: false
    cmds:
      - docker cp ledger_bkp.dump postgres:/tmp/mydb_dump.bin &> /dev/null
      - |
        docker exec postgres psql -U ledger -d postgres -c "DROP DATABASE IF EXISTS ledger;" &> /dev/null 
        docker exec postgres psql -U ledger -d postgres -c "CREATE DATABASE ledger;" &> /dev/null
        docker exec postgres pg_restore -U ledger -d ledger -v /tmp/mydb_dump.bin &> /dev/null
    silent: true
        





